version: '2'
services:
    kukulkan-mongodb:
        extends:
            file: mongodb.yml
            service: kukulkan-mongodb
    kukulkan-mysql:
        extends:
            file: mysql.yml
            service: kukulkan-mysql
    kukulkan-ngix:
        extends:
            file: nginx-local.yml
            service: kukulkan-nginx