version: '2'
services:
    kukulkan-app:
        image: kukulkan:latest
        depends_on: 
            - kukulkan-mongodb
            - kukulkan-mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://kukulkan-mongodb:27017
            - KUKULKAN_DATA_MYSQL_URI=jdbc:mysql://kukulkan-mysql:3306
            - KUKULKAN_MODELER_URI=http://kukulkan-modeler
            - KUKULKAN_OUTPUTDIR=/home/app/
        ports:
            - 8080:8080
        volumes:
            - ~/webapp/:/home/generator/
    kukulkan-mongodb:
        extends:
            file: mongodb.yml
            service: kukulkan-mongodb
    kukulkan-mysql:
        extends:
            file: mysql.yml
            service: kukulkan-mysql
    kukulkan-ngix:
        extends:
            file: nginx.yml
            service: kukulkan-nginx